// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEtuF3PZdFpJ2pMG6WJQ3yKCAW0sz3a1g',
    appId: '1:864808171743:web:7f28591fce00025ee4916a',
    messagingSenderId: '864808171743',
    projectId: 'fitforge-96786',
    authDomain: 'fitforge-96786.firebaseapp.com',
    storageBucket: 'fitforge-96786.firebasestorage.app',
    measurementId: 'G-97TZJ8KF6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1S5ZjDXbM0Zw0Cz1kTjVDQ3KLpJorr10',
    appId: '1:864808171743:android:24964b45e6a08b79e4916a',
    messagingSenderId: '864808171743',
    projectId: 'fitforge-96786',
    storageBucket: 'fitforge-96786.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAieqGmfjfFnqSBf1kf_bDUZ9rzsbCcg-0',
    appId: '1:864808171743:ios:f332df70716c92d7e4916a',
    messagingSenderId: '864808171743',
    projectId: 'fitforge-96786',
    storageBucket: 'fitforge-96786.firebasestorage.app',
    iosBundleId: 'com.example.fitforge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAieqGmfjfFnqSBf1kf_bDUZ9rzsbCcg-0',
    appId: '1:864808171743:ios:f332df70716c92d7e4916a',
    messagingSenderId: '864808171743',
    projectId: 'fitforge-96786',
    storageBucket: 'fitforge-96786.firebasestorage.app',
    iosBundleId: 'com.example.fitforge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEtuF3PZdFpJ2pMG6WJQ3yKCAW0sz3a1g',
    appId: '1:864808171743:web:08cfdc5b824d6747e4916a',
    messagingSenderId: '864808171743',
    projectId: 'fitforge-96786',
    authDomain: 'fitforge-96786.firebaseapp.com',
    storageBucket: 'fitforge-96786.firebasestorage.app',
    measurementId: 'G-9GZ54KWXEJ',
  );
}
